version: 2.1
orbs:
  gem: zfhui/ruby-gem@0.2.1

jobs:
  test-with-ruby-latest:
    working_directory: ~/repo
    executor:
      name: gem/default
      tag: latest
    steps:
      - gem/setup-and-test:
          gemspec: silent_ping.gemspec
          bundler-version: 2.0.1
  test-with-ruby-2-6-5:
    working_directory: ~/repo
    executor:
      name: gem/default
      tag: 2.6.5
    steps:
      - gem/setup-and-test:
          gemspec: silent_ping.gemspec
          bundler-version: 2.0.1
  test-with-ruby-2-3-6:
    working_directory: ~/repo
    executor:
      name: gem/default
      tag: 2.3.6
    steps:
      - gem/setup-and-test:
          gemspec: silent_ping.gemspec
          bundler-version: 1.16.1
  build-and-release:
    working_directory: ~/repo
    executor: gem/default
    steps:
      - gem/build:
          gem-name: silent_ping
      - gem/release:
          gem-name: silent_ping
          gem-credentials-env-name: $RUBYGEMS_API_KEY

workflows:
  test-build-and-deploy:
    jobs:
      - test-with-ruby-latest
      - test-with-ruby-2-6-5
      - test-with-ruby-2-3-6
      - build-and-release:
          requires:
          - test-with-ruby-latest
          - test-with-ruby-2-6-5
          - test-with-ruby-2-3-6
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
