version: 2.1
jobs:
  build:
    docker:
    - image: circleci/ruby:2.6.3-stretch-node
    steps:
    - checkout
    - restore_cache:
        keys:
          - gem-cache-{{ checksum "silent_ping.gemspec" }}
          - gem-cache-
    - run:
        name: Install new Bundler
        command: gem install bundler
    - run:
        name: Bundle Install
        command: bundle install --jobs=4 --retry=3 --path=vendor/bundle
    - save_cache:
        key: gem-cache-{{ checksum "silent_ping.gemspec" }}
        paths:
          - vendor/bundle
    - run:
        name: RSpec
        command: bundle exec rspec --format progress spec
